# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homebase', '0003_auto_20171020_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sf', 'Single Full Cover'), ('sp', 'Single Partial Cover'), ('pf', 'Permanent Full Cover'), ('pp', 'Permanent Partial Cover')], default='', max_length=2)),
                ('sobstory', models.TextField(default='')),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_poster', to='homebase.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('shift_date', models.DateField()),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('location', models.CharField(choices=[('ma', 'Marshburn Library'), ('da', 'Darling Library'), ('st', 'Stamps Library'), ('sd', 'Support Desk'), ('rc', 'Repair Center'), ('md', 'MoD Desk'), ('ss', 'Senior Support Techs')], default='ma', max_length=2)),
                ('is_open', models.BooleanField(default=False)),
                ('checked_in', models.CharField(choices=[('F', 'Not Checked In'), ('T', 'Checked In'), ('O', 'Out of Office'), ('W', 'West Campus'), ('E', 'East Campus'), ('A', 'Off Campus'), ('R', 'Regional Campus'), ('S', 'Refresh Day')], default='F', max_length=1)),
                ('google_id', models.TextField(default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_owner', to='homebase.Employees')),
                ('perm_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.PermanentShifts')),
            ],
        ),
        migrations.AddField(
            model_name='shiftcovers',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Shifts'),
        ),
        migrations.AddField(
            model_name='shiftcovers',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_taker', to='homebase.Employees'),
        ),
    ]
