# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=2)),
                ('token', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='shiftcovers',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='id',
        ),
        migrations.AddField(
            model_name='shifts',
            name='event_id',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='location',
            field=models.CharField(choices=[('ma', 'Marshburn Library'), ('da', 'Darling Library'), ('st', 'Stamps Library'), ('sd', 'Support Desk'), ('sr', 'Support Reps'), ('rc', 'Repair Center'), ('md', 'MoD Desk'), ('ss', 'Senior Support Techs'), ('sf', 'Staff'), ('te', 'TESTING')], default='ma', max_length=2),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='perm_id',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='PermanentShifts',
        ),
    ]
