# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_auto_20171220_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifts',
            old_name='perm_id',
            new_name='permanent_id',
        ),
        migrations.AlterField(
            model_name='shifts',
            name='event_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
