# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0008_auto_20180102_1134'),
        ('shifts', '0003_auto_20171220_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('na', 'No Action'), ('fpp', 'Full Permanent Post'), ('fsp', 'Full Single Post'), ('ppp', 'Partial Permanent Post'), ('psp', 'Partial Single Post'), ('fpt', 'Full Permanent Take'), ('fst', 'Full Single Take'), ('ppt', 'Parital Permanent Take'), ('pst', 'Partial Single Take')], default='na', max_length=3)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees')),
            ],
        ),
        migrations.RemoveField(
            model_name='shiftcovers',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='shiftcovers',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='shiftcovers',
            name='taker',
        ),
        migrations.AddField(
            model_name='shifts',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shifts',
            name='sob_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='location',
            field=models.CharField(choices=[('ma', 'Marshburn'), ('da', 'Darling'), ('st', 'Stamps'), ('sd', 'Support Desk'), ('sr', 'Support Reps'), ('rc', 'Repair Center'), ('md', 'MoD Desk'), ('ss', 'Senior Support Techs'), ('sf', 'Staff'), ('te', 'TESTING')], default='ma', max_length=2),
        ),
        migrations.DeleteModel(
            name='ShiftCovers',
        ),
        migrations.AddField(
            model_name='shiftrecords',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Shifts'),
        ),
    ]
