# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0008_auto_20180102_1134'),
        ('shifts', '0005_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees')),
            ],
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='delete',
        ),
    ]
