# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0008_auto_20180102_1134'),
        ('shifts', '0005_holidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='delete',
        ),
    ]
