# Generated by Django 2.0 on 2018-03-13 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_auto_20180108_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
