# Generated by Django 2.0 on 2018-03-15 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_shifts_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='checkin_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
