# Generated by Django 2.0 on 2018-03-20 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_auto_20180320_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
    ]
