# Generated by Django 2.0 on 2018-04-26 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('na', 'No Action'), ('fpp', 'Full Permanent Post'), ('fsp', 'Full Single Post'), ('ppp', 'Partial Permanent Post'), ('psp', 'Partial Single Post'), ('fpt', 'Full Permanent Take'), ('fst', 'Full Single Take'), ('ppt', 'Parital Permanent Take'), ('pst', 'Partial Single Take')], default='na', max_length=3)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('event_id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('shift_date', models.DateField()),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('location', models.CharField(choices=[('ma', 'Marshburn'), ('da', 'Darling'), ('st', 'Stamps'), ('sd', 'Support Desk'), ('sr', 'Support Reps'), ('rc', 'Repair Center'), ('md', 'MoD Desk'), ('ss', 'Senior Support Techs'), ('sf', 'Staff'), ('te', 'TESTING')], default='ma', max_length=2)),
                ('is_open', models.BooleanField(default=False)),
                ('checked_in', models.CharField(choices=[('F', 'Not Checked In'), ('T', 'Checked In'), ('O', 'Out of Office'), ('W', 'West Campus'), ('E', 'East Campus'), ('A', 'Off Campus'), ('R', 'Regional Campus'), ('S', 'Refresh Day')], default='F', max_length=1)),
                ('checkin_time', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('permanent_id', models.TextField(default='')),
                ('sob_story', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_owner', to='homebase.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='SyncTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=2)),
                ('token', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='shiftrecords',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Shifts'),
        ),
    ]
