# Generated by Django 2.0 on 2018-04-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField(default='')),
                ('body', models.TextField(default='')),
                ('sticky', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('netid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=30)),
                ('lname', models.CharField(default='', max_length=30)),
                ('delete', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('apuid', models.CharField(default='', max_length=11)),
                ('codename', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('position', models.CharField(choices=[('lbt', 'Lab Technician'), ('spt', 'Support Tech'), ('sst', 'Senior Support Tech'), ('sdr', 'Support Desk Rep'), ('llt', 'Lead Lab Tech'), ('mgr', 'Manager'), ('stt', 'Staff Tech'), ('stm', 'Staff Manager')], default='lbt', max_length=40)),
                ('position_desc', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('standing', models.CharField(choices=[('fr', 'Freshman'), ('sp', 'Sophomore'), ('jr', 'Junior'), ('sr', 'Senior'), ('ss', 'Super-Senior!'), ('st', 'Staff'), ('us', 'Unspecified')], default='us', max_length=2)),
                ('favcandy', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('aboutme', models.TextField(blank=True, default='', null=True)),
                ('notify_level', models.IntegerField(default=2)),
                ('developer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('event_date', models.DateField()),
                ('location', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FailBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail_type', models.CharField(choices=[('bs', 'Most Bad Sectors'), ('mj', 'Most Journals'), ('bn', 'Most Bad News Deliveries'), ('cc', 'Largest cCleaner Total Size Removed'), ('db', 'Longest Backup Time'), ('st', 'Strangest Error'), ('mv', 'Most Viruses'), ('mf', 'Worst MoD Fail'), ('ld', 'Longest Defrag'), ('bc', 'Best Comment'), ('lv', 'Longest Virus Scan')], max_length=30)),
                ('fail_val', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageFromThePast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotifySources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('e', 'email'), ('s', 'Slack'), ('t', 'Text Message')], default='e', max_length=1)),
                ('details', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('netid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homebase.Employees')),
                ('status', models.CharField(choices=[('i', 'In Office'), ('o', 'Out of Office'), ('e', 'East Campus'), ('w', 'West Campus'), ('f', 'Off Campus'), ('m', 'Meeting')], default='o', max_length=1)),
                ('description', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='notifysources',
            name='netid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees'),
        ),
        migrations.AddField(
            model_name='failboard',
            name='fail_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees'),
        ),
        migrations.AddField(
            model_name='events',
            name='announcer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='announcer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees'),
        ),
    ]
