# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(default='', max_length=15)),
                ('print_ip', models.URLField(max_length=14)),
                ('print_type', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printinfo.Location')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 10, 11, 19, 14, 28), verbose_name='Date')),
                ('print_stat', models.CharField(choices=[('healthy', 'All Good'), ('warning', 'Alert!'), ('down', 'Printer Down!')], max_length=12)),
                ('desc', models.TextField(default='', max_length=300)),
                ('netid', models.ForeignKey(default='nchera13', on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees')),
                ('print_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printinfo.Printer')),
            ],
        ),
    ]
