# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 19, 14, 48), verbose_name='Date'),
        ),
    ]
