# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printinfo', '0003_auto_20171116_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 10, 35, 17), verbose_name='Date'),
        ),
    ]
