# Generated by Django 2.0 on 2018-06-04 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printinfo', '0004_auto_20180105_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 11, 50, 22), verbose_name='Date'),
        ),
    ]
