# Generated by Django 2.0 on 2018-04-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('lab', 'Lab Access'), ('sup', 'Support Access'), ('mgr', 'Manager Access'), ('dev', 'Developer Access'), ('all', 'All access'), ('non', 'No Access (hide)')], default='non', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('passwd', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('permission', models.IntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='passpermission',
            name='pass_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwords.Passwords'),
        ),
    ]
