# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start',
            field=models.DateField(),
        ),
    ]
