# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePrices',
        ),
    ]
