# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0002_auto_20170808_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophies',
            name='giver',
        ),
        migrations.RemoveField(
            model_name='trophies',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Trophies',
        ),
    ]
