# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='eventEnd',
            new_name='event_end',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='eventStart',
            new_name='event_start',
        ),
        migrations.RenameField(
            model_name='shifts',
            old_name='shiftEnd',
            new_name='shift_end',
        ),
        migrations.RenameField(
            model_name='shifts',
            old_name='shiftStart',
            new_name='shift_start',
        ),
        migrations.AddField(
            model_name='employee',
            name='developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trophies',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emailsubscriptions',
            name='bio_sub',
            field=models.CharField(choices=[('no', 'No Emails'), ('lb', 'Lab Emails'), ('al', 'All Emails')], default='none', max_length=2),
        ),
        migrations.AlterField(
            model_name='emailsubscriptions',
            name='shift_sub',
            field=models.CharField(choices=[('no', 'No Emails'), ('lb', 'Lab Tech Emails'), ('sd', 'Support Desk Emails'), ('rc', 'Repair Center Emails'), ('al', 'All Emails!')], default='lab', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('lbt', 'Lab Technician'), ('spt', 'Support Tech'), ('sst', 'Senior Support Tech'), ('llt', 'Lead Lab Tech'), ('man', 'Manager'), ('stt', 'Staff Tech'), ('stm', 'Staff Manager')], default='lbt', max_length=40),
        ),
        migrations.AlterField(
            model_name='trophies',
            name='trophy_type',
            field=models.CharField(choices=[('mil', 'Milestone'), ('bdg', 'Badge'), ('udb', 'Under the Bus'), ('str', 'Star'), ('hst', 'Half-Star'), ('mas', 'Mastery')], default='', max_length=3),
        ),
    ]
