# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0002_auto_20171013_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='coverFor',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Shifts',
        ),
    ]
