# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0003_auto_20170808_1547'),
        ('homebase', '0003_auto_20170816_1250'),
    ]

    operations = [
    ]
