# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0004_auto_20171110_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='subject',
            field=models.TextField(default='Announcement'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start',
            field=models.DateField(),
        ),
    ]
