# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0005_auto_20171116_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwords',
        ),
    ]
