# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0006_delete_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('o', 'Out of Office'), ('f', 'Off Campus'), ('e', 'East Campus'), ('w', 'West Campus'), ('i', 'In Office')], default='o', max_length=1)),
                ('description', models.CharField(default='', max_length=20)),
                ('netid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees')),
            ],
        ),
    ]
