# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0007_staffstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('lbt', 'Lab Technician'), ('spt', 'Support Tech'), ('sst', 'Senior Support Tech'), ('sdr', 'Support Desk Rep'), ('llt', 'Lead Lab Tech'), ('mgr', 'Manager'), ('stt', 'Staff Tech'), ('stm', 'Staff Manager')], default='lbt', max_length=40),
        ),
        migrations.AlterField(
            model_name='staffstatus',
            name='netid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homebase.Employees'),
        ),
    ]
