# Generated by Django 2.0 on 2018-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0008_auto_20180102_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='netid',
        ),
        migrations.DeleteModel(
            name='BrowserStats',
        ),
        migrations.RenameField(
            model_name='announcements',
            old_name='announcement',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_end',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_start',
        ),
        migrations.AlterField(
            model_name='announcements',
            name='subject',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staffstatus',
            name='status',
            field=models.CharField(choices=[('i', 'In Office'), ('o', 'Out of Office'), ('e', 'East Campus'), ('w', 'West Campus'), ('f', 'Off Campus'), ('m', 'Meeting')], default='o', max_length=1),
        ),
        migrations.DeleteModel(
            name='Access',
        ),
    ]
