# Generated by Django 2.0 on 2018-03-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0010_auto_20180322_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifysources',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
