# Generated by Django 2.0 on 2018-06-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0011_notifysources_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('completer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskCompleter', to='homebase.Employees')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskPoster', to='homebase.Employees')),
            ],
        ),
    ]
