# Generated by Django 2.0 on 2018-06-08 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0012_modtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modtasks',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='modtasks',
            name='completer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskCompleter', to='homebase.Employees'),
        ),
        migrations.AlterField(
            model_name='modtasks',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
