# Generated by Django 2.0 on 2018-05-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0012_modtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modtasks',
            old_name='author',
            new_name='poster',
        ),
    ]
