# Generated by Django 2.0 on 2018-06-26 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0013_auto_20180608_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notePoster', to='homebase.Employees')),
            ],
        ),
    ]
