# Generated by Django 2.0 on 2018-06-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0014_auto_20180608_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modtasks',
            name='completer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskCompleter', to='homebase.Employees'),
        ),
    ]
