# Generated by Django 2.0 on 2018-06-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0015_auto_20180608_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='modtasks',
            name='testing',
            field=models.BooleanField(default=False),
        ),
    ]
