# Generated by Django 2.0 on 2018-06-08 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0017_auto_20180608_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(null=True)),
                ('completer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskCompleter', to='homebase.Employees')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskPoster', to='homebase.Employees')),
            ],
        ),
    ]
