# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('passwd', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('permission', models.IntegerField(default=3)),
            ],
        ),
    ]
