# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('lab', 'Lab Access'), ('sup', 'Support Access'), ('mgr', 'Manager Access'), ('dev', 'Developer Access'), ('all', 'All access'), ('non', 'No Access (hide)')], default='non', max_length=3)),
                ('pass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwords.Passwords')),
            ],
        ),
    ]
