# Generated by Django 2.0 on 2018-08-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_passpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='permission',
        ),
    ]
