# Generated by Django 2.0 on 2018-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_remove_passwords_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='permission',
            field=models.IntegerField(default=3),
        ),
    ]
