# Generated by Django 2.0 on 2018-04-26 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('print_ip', models.URLField(max_length=14)),
                ('type', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printinfo.Location')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('print_stat', models.CharField(choices=[('healthy', 'All Good'), ('warning', 'Alert!'), ('down', 'Printer Down!')], max_length=12)),
                ('desc', models.TextField(default='', max_length=300)),
                ('netid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printinfo.Printer')),
            ],
        ),
    ]
