# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=20)),
                ('inuse', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('placement_order', models.IntegerField(default=0)),
            ],
        ),
    ]
