# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20170829_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprices',
            old_name='service',
            new_name='service_name',
        ),
    ]
