"""
Django settings for sidekick project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import logging.config
import os

PRODUCTION = os.environ.get('SK_PRODUCTION', 'False') == "True"

if PRODUCTION:
    print("Using SSL Encryption")
    SECURE_PROXY_SSL_HEADER = ('HTTPS_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    print("Using standard HTTP")
    SECURE_PROXY_SSL_HEADER = None
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    # if os.environ['SK_DUMMY']:


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SK_SECRET_KEY', 'changeme')

# Location of client_secret.json goes here
GOOGLE_OAUTH2_CLIENT_SECRETS_JSON = os.environ.get('GOOGLE_CLIENT_SECRET', '/some/path')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('SK_DEBUG', 'True') == "True"

ALLOWED_HOSTS = [
    '192.168.8.33',
    'sidekick.devel.apu.edu',
    '127.0.0.1',
    '192.168.8.7',
    'sidekick.apu.edu',
]


# Application definition

INSTALLED_APPS = [
    'homebase.apps.HomebaseConfig',
    'passwords.apps.PasswordsConfig',
    'printinfo.apps.PrintinfoConfig',
    'quotes.apps.QuotesConfig',
    'roster.apps.RosterConfig',
    'shifts.apps.ShiftsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cas.apps.CASConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'cas.middleware.CASMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sidekick.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sidekick.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB', 'sidekick'),
        'USER': os.environ.get('POSTGRES_USER', 'sidekick_admin'),
        'PASSWORD': os.environ.get('POSTGRES_PASS', 'Pl@typusL0vesslurp33s'),
        'HOST': os.environ.get('POSTGRES_HOST', 'skdb.devel.apu.edu'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432')
    }
}

# Authentication
CAS_SERVER_URL = os.environ.get('CAS_URL', 'http://example.com')
CAS_LOGOUT_COMPLETELY = True
CAS_PROVIDE_URL_TO_LOGOUT = True
CAS_FORCE_SSL_SERVICE_URL = False

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'cas.backends.CASBackend'
]

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', '/static/')

if PRODUCTION:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
else:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static")
    ]

# Google Cal Settings
CALENDAR_LOCATION_IDS = {
    'ma': os.environ.get('CAL_ID_MA', ''),
    'da': os.environ.get('CAL_ID_DA', ''),
    'st': os.environ.get('CAL_ID_ST', ''),
    'sd': os.environ.get('CAL_ID_SD', ''),
    'rc': os.environ.get('CAL_ID_RC', ''),
    'md': os.environ.get('CAL_ID_MD', ''),
    'te': os.environ.get('CAL_ID_TE', '')
}

LOGGING_CONFIG = None

"""
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
        'logfile': {
            'class': 'logging.FileHandler',
            'formatter': 'console',
            'filename': 'sk_log.log'
        },
        'email': {
            'class': 'logging.handlers.SMTPHandler',
            'formatter': 'console',
            'mailhost': (os.environs.get('MAIL_HOST'), os.environs.get('MAIL_PORT')),
            'fromaddr': 'bugmaster@sidekick.apu.edu',
            'toaddrs': [os.environ.get('bugaddr', 'changeme@example.com')],
            'subject': 'Bug report!',
        }
    },
    'loggers': {
        '': {
            'level': 'WARNING',
            'handlers': ['console', 'logfile'],
        },
        'django': {
            'level': 'ERROR',
            'handlers': ['email', 'logfile']
        }
    },
})
"""


# Email Server settings
EMAIL_HOST = os.environ.get('MAIL_HOST', 'mail.example.com')
EMAIL_PORT = os.environ.get('MAIL_PORT', '25')
EMAIL_SUBJECT_PREFIX = "[IMTDS] "

HARAMBOT_NOTIFY = os.environ.get('HARAMBOT_NOTIFY_TARGET', '')
