# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homebase', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('trophy_type', models.CharField(choices=[('bdg', 'Badge'), ('str', 'Star')], default='', max_length=3)),
                ('icon', models.CharField(default='', max_length=30)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophyGiver', to='homebase.Employees')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophyRecipient', to='homebase.Employees')),
            ],
        ),
    ]
