# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0004_auto_20171110_1559'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('val', models.DecimalField(decimal_places=2, max_digits=3)),
                ('violation', models.CharField(default='', max_length=15)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_about', to='homebase.Employees')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_poster', to='homebase.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.IntegerField(default=0)),
                ('advanced', models.IntegerField(default=0)),
                ('field', models.IntegerField(default=0)),
                ('printer', models.IntegerField(default=0)),
                ('network', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(default=0)),
                ('refresh', models.IntegerField(default=0)),
                ('software', models.IntegerField(default=0)),
                ('netid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Employees')),
            ],
        ),
    ]
