# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_discipline_proficiencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='violation',
        ),
        migrations.AddField(
            model_name='discipline',
            name='subject',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
